
// This file has been generated by the GUI designer. Do not modify.
namespace SharpKernelUpdate
{
	public partial class SharpKernelUpdateWindow
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget SharpKernelUpdate.SharpKernelUpdateWindow
			this.Name = "SharpKernelUpdate.SharpKernelUpdateWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("SharpKernelUpdateWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
